### ISSUE TITLE
Percentage vs percentage points

### ISSUE THREAD

**Issue by srinivvenkat** [nikosbosse/Metaculus-Twitter-bot#10]
For questions involving percentages, is the difference in percentage points (6% -> 12% would be 6 pp instead of 100% increase)? I think that is more intuitive, and if it's already that, perhaps the tweet can explicitly say 'pp.'

**Comment by nikosbosse** [comment]
Definitely agree that percentage points is more precise. It is, however, also longer and 'pp' is also not that intuitive. I'm wondering whether, together with the plot, this actually does confuse people a lot. % looks cleaner, but pp is more correct. I'm on the fence. @edomt , @adam-binks what do you think?

**Comment by edomt** [comment]
I'm unsure as well 🤷🏻‍♂️ 
But as long as not too many people complain, I think I favor keeping the more legible (although less accurate) `+X%`

**Comment by adam-binks** [comment]
Yeah I think pp might be a bit confusing - one option is to say

Will Russia control Kyiv on June 1, 2022?

Community prediction: 48%
⬇️ -12% in the last 24 hours **(from 60%)**

**Comment by nikosbosse** [comment]
Also a good idea. Let's see whether others also complain / find it confusing. 
@srinivvenkat I'll close it for now, but please do feel very welcome to open again if you have a strong opinion on this!

**Comment by srinivvenkat** [comment]
I like @adam-binks 's suggestion. It addresses the main concern I had.
