### ISSUE TITLE
Fix tweeting of new forecasts

### ISSUE THREAD

**Issue by nikosbosse** [nikosbosse/Metaculus-Twitter-bot#15]
The bot currently tweets new questions up to 2 times, which is not ideal. Current issue: 
- the minimum_hours is set to 48 to make sure that the question was already at least 24 hours old before we compare its past value to the one now. So in order to get labelled as 'change' the question needs to be at least 48 hours old. 
- The 'new question' tweet ignores that and tweets it right away, then waits 24h because of the no-tweet-period and then tweets it again as new. Then in the next cycle it would be labelled as 'change'. 

Some thoughts: 
- I was thinking that maybe the requirement we really want is that a question must have x (currently 10, maybe 8?) forecasts at the first time point against which it is compared. So maybe it is fine for a question to published at t=0, it has 10 forecasts at t=10 and we tweet about a change in 24h at t=34 (or a change in 5h at t=15)? 
- So we could tweet it as 'new' iff a question has a) more than 10 forecasts and b) didn't have more than 10 forecasts 24h ago? And if it has more than 10 forecasts at both time points it would be a regular change? 
- Downsides: a) it could (in theory) happen that a forecast gets tweeted as new when it crosses the threshold after a month or so (could also add a time requirement). b) This would however make the code potentially more complicated. 

What do you think @Scott-Huston, @edomt, @adam-binks?

**Comment by adam-binks** [comment]
I haven't looked at the code but was wondering if you could expand a bit on this:

> The 'new question' tweet ignores that and tweets it right away, then waits 24h because of the no-tweet-period and then tweets it again as new. Then in the next cycle it would be labelled as 'change'.

Why does it tweet it again as new after 24h?

**Comment by edomt** [comment]
It seems to me that the only real downside about the current situation is the double-tweeting of "New question" alerts (which happens a first time between h0 and h6, and then a second time between h24 and h30).

So I think we want to avoid that, which is fairly simple to do (here's a PR for it: https://github.com/nikosbosse/Metaculus-Twitter-bot/pull/17).

Other than that, I _think_ it's good not to relax the `minimum_hours` threshold for now: it seems that forecasts less than 48 hours old tend to swing a lot, even with a decent number of forecasts made.
