### ISSUE TITLE
Fix double posting

### ISSUE THREAD

**Issue by nikosbosse** [nikosbosse/Metaculus-Twitter-bot#24]
We recently had an issue with the Metaculus Alert bot double posting stuff, see https://twitter.com/MetaculusAlert/status/1563949726097195008. 

What I did for now was just deactivate the bot altogether because I'm currently absolutely swamped with things, but that's of course not ideal. Does anyone have time to take a quick look at what might have happened and how to fix it? 
@edomt @adam-binks @Scott-Huston
Thank you very much!

**Comment by edomt** [comment]
I have a pretty clear idea for a fix that won't be too difficult to implement. Instead of checking already-tweeted alerts based on the question title, we can keep a tiny 'database' of recent alerts as a CSV file, and compare timestamps before tweeting.

I'll work on a PR today.
