### ISSUE TITLE
Bot claims large increase every day without large increase

### ISSUE THREAD

**Issue by dskloet** [nikosbosse/Metaculus-Twitter-bot#28]
For 6 days in a row, the bot has claimed double digit percent increases in this one question while the actual prediction increased only from 31% to 35% in this time.

https://twitter.com/MetaculusAlert/status/1604718578200199173
https://twitter.com/MetaculusAlert/status/1605141407894839296
https://twitter.com/MetaculusAlert/status/1605533993025372160
https://twitter.com/MetaculusAlert/status/1605986967421861904
https://twitter.com/MetaculusAlert/status/1606439947615043585
https://twitter.com/MetaculusAlert/status/1606892905544794115

https://www.metaculus.com/questions/11243/russian-military-deaths-by-2024/?sub-question=10557

**Comment by nikosbosse** [comment]
Hi @dskloet, thanks for creating an issue! We're working on it (#29)
