### ISSUE TITLE
Improve tweet text

### ISSUE THREAD

**Issue by nikosbosse** [nikosbosse/Metaculus-Twitter-bot#3]
Make text easier to skim by 
- adding emojis
- potentially add a screenshot / plot

One proposal: 
![image](https://user-images.githubusercontent.com/37978797/156454770-c62061f1-5a03-4959-9d7e-6794f01d87b7.png)

**Comment by edomt** [comment]
@nikosbosse I can do some work on this tonight if you haven't started!

**Comment by nikosbosse** [comment]
Amazing, yes please!

**Comment by edomt** [comment]
https://github.com/nikosbosse/Metaculus-Twitter-bot/pull/6 takes care of improving the text.
I'm working on a second PR (probably done tomorrow) to recreate the Metaculus plot and upload it with each tweet.

**Comment by yiqinfu** [comment]
Second this suggestion! Would also be great if you could either remove the intro text ("The Metaculus community prediction on") or add a line break before it and the question text. Personally I feel like the intro text makes the tweets hard to read.

**Comment by nikosbosse** [comment]
Addressed by #6. Thank you, @edomt! 
Closing for now.
