### ISSUE TITLE
Automatically get list of relevant questions

### ISSUE THREAD

**Issue by nikosbosse** [nikosbosse/Metaculus-Twitter-bot#4]
Currently the questions to check are hard-coded. One could get a list of all open questions from the API here (https://www.metaculus.com/api2/questions/). Ideally, this should be queried using the URL to avoid a lot of unnecessary computations for the bot.

**Comment by edomt** [comment]
The easiest way to fetch all questions from the Ukraine tournament seems to be https://www.metaculus.com/api2/questions/?project=1426&status=open&type=forecast&limit=999

And we could add a few hardcoded questions on top of that list, e.g. https://www.metaculus.com/questions/2797/will-no-non-test-nuclear-weapons-be-detonated-by-start-of-2024/

**Comment by nikosbosse** [comment]
Nice, this is really good!
For now we would also have to filter for binary questions (there is field called possibilities with a subfield called "type" in the JSON). My JSON game isn't good enough to filter it using a URL. Would something like this
```
https://www.metaculus.com/api2/questions/?project=1426&status=open&type=forecast&limit=999&possibilities:type=%22binary%22
``` 
do?

**Comment by edomt** [comment]
Ha, didn't know that! I'm not sure the API parameters include a filter on that field.
But we can fetch https://www.metaculus.com/api2/questions/?project=1426&status=open&type=forecast&limit=999 and then:

```python
for question in response["results"]:
    if question["possibilities"]["type"] == "binary":
         # process question
```

**Comment by nikosbosse** [comment]
yes, that also works. I was thinking more long-term. In case we wanted to expand the bot to all existing Metaculus questions, it would be easiest if we could filter for open questions, binary questions etc. using a URL to save the bot from having to access everything. 

But you're probably right and it we could just solve this in python for now :)

**Comment by edomt** [comment]
Yes, definitely. Do you know if the API is actually documented anywhere? Otherwise, we can simply ask the Metaculus team if it's possible to get that filter at some point in the future.

**Comment by nikosbosse** [comment]
The API documentation is on Metaculus' to do list... I just asked and they confirmed that's not possible at the moment. So filtering in python is the way to go :)
